### ISSUE TITLE
Howto Enable SSL for postgres client connections

### ISSUE THREAD

**Issue by Elexy** [lwolf/stolon-chart#4]
I am looking for a way to enable ssl certs for postgres client connections.
Looks like it can be done with stolonctl pgparameters.

Would it be in the scope of this project to make that an option in the chart?

**Comment by lwolf** [comment]
It is not something I need right now, but pull requests are very welcome

**Comment by Elexy** [comment]
I'll let you know what I come up with.

**Comment by royeectu** [comment]
Hi guys,
Do you have any updates regarding this issue? I would really like to use this project but without SSL support it is useless for me.

**Comment by Elexy** [comment]
I have it working in my cluster, just haven't had time to do the PR. To help you out a bit until I get time, here is a small writeup.

I followed the postgres docs on creating key and crt files, then created a secret containing these files in clusters. This is how I added it into the keep yaml:
```
{{- if .Values.keeper.client_ssl.enabled }}
        - mountPath: /etc/secrets/ssl
          name: certs
{{- end }}
        resources:
{{ toYaml .Values.keeper.resources | indent 10 }}
      volumes:
        - name: stolon
          secret:
            secretName: {{ template "fullname" . }}
{{- if .Values.keeper.client_ssl.enabled }}
        - name: certs
          secret:
            secretName: {{ .Values.keeper.client_ssl.certs_secret_name }}
            defaultMode: 0600
{{- end }}
```
changed the command like this:
```
            ....
            export STOLON_DATA=/stolon-data
            chown stolon:stolon $STOLON_DATA
{{- if .Values.keeper.client_ssl.enabled }}
            chown -R stolon:stolon /etc/secrets/ssl
{{- end }}
            exec gosu stolon stolon-keeper --data-dir $STOLON_DATA
```
Also change the job that creates the cluster:
```
          - init
          - --cluster-name={{ .Values.clusterName }}
          - --store-backend={{ .Values.store.backend }}
          - --store-endpoints=http://{{ .Values.store.endpoint }}:2379
          - --yes
  {{- if .Values.keeper.client_ssl.enabled }}
          - '{  "initMode": "new", "pgParameters": { "ssl": "on", "ssl_cert_file": "/etc/secrets/ssl/server.crt", "ssl_key_file": "/etc/secrets/ssl/server.key"{{ if .Values.slow_queries.enabled }}, "log_min_duration_statement" :  "{{ .Values.slow_queries.min_duration }}" {{ end }} } }'
  {{- else if .Values.slow_queries.enabled }}
          - '{  "initMode": "new", "pgParameters": { "log_min_duration_statement" :  {{ .Values.slow_queries.min_duration }} } }'
  {{- end }}
```
***beware, this also includes the query logging of >100ms*** just remove  "log_min_duration_statement" :  "{{ .Values.slow_queries.min_duration }}" if you don't want that.

add this to the values.yaml under the `keeper` key:
```
 ## configure ssl for client access
  # create certificates according to these instructions: https://www.postgresql.org/docs/9.6/static/ssl-tcp.html
  # to enable encrypted traffic, servert.crt and server.key are required
  # the use of ** Client Certificates ** is not supported
  client_ssl:
    enabled: false
    certs_secret_name: pg-cert-secret
```
for slow queries add:
```
## log slow queries
# disabled by default
slow_queries:
  enabled: false
  min_duration: 300
```
Hope that helps. I'm swamped right now :-)
